### ISSUE TITLE
Expose Stream Callbacks

### ISSUE THREAD

**Issue by bheisler** [bheisler/RustaCUDA#13]
CUDA streams can enqueue a host-side callback which will be called when the stream reaches that point in the work queue. RustaCUDA does not currently support this.

[Stream Management](https://docs.nvidia.com/cuda/archive/8.0/cuda-driver-api/group__CUDA__STREAM.html#group__CUDA__STREAM)

Note that we'll have to ensure that the callback code doesn't allow panics to reach the CUDA driver.

**Comment by rusch95** [comment]
My current stab at it seems to be working, as the Hello World callback I threw inside launch.rs is printing without segfaulting. I'll post code soon after twiddling it a bit more and writing some more tests.

**Comment by bheisler** [comment]
Fixed by #14.
