### ISSUE TITLE
Question: Problem finding lcudart and lcublas when building example Ubuntu 18.04

### ISSUE THREAD

**Issue by mstallmo** [bheisler/RustaCUDA#15]
I've just been poking around with the example from https://bheisler.github.io/post/announcing-rustacuda/ and I keep running into some build issues with cuda-rs. I've set `$CUDA_LIBRARY_PATH` to the location of CUDA on my system (/usr/local/cuda/lib64) and when running `cargo build` I get the following error: 
`  note: /usr/bin/ld: cannot find -lcudart
          /usr/bin/ld: cannot find -lcublas
          collect2: error: ld returned 1 exit status`

Any help would be greatly appreciated!

**Comment by rusch95** [comment]
Try just LIBRARY_PATH instead.

**Comment by mstallmo** [comment]
@rusch95 Worked like a charm! Thanks!

**Comment by bheisler** [comment]
@rusch95 Why does that work?

**Comment by rusch95** [comment]
@bheisler Rust uses `ld` to link static libraries, which also searches `LIBRARY_PATH`, in addition to the standard locations, when linking static libraries. 

Also, it looks like `CUDA_LIBRARY_PATH` for cuda-sys is currently broken on Ubuntu 18.04, at least by my experience.

**Comment by SuperFluffy** [comment]
Small nitpick and for future reference: `ld` does not search `LIBRARY_PATH` itself. It looks for `LIBRARY_PATH` when invoked by `gcc` in linking mode, akin to `ld -lcublas -L/opt/cuda/lib64`.

**Comment by alphastrata** [comment]
> Try just LIBRARY_PATH instead.

Can we add this to the README.md ? (A lot of users of this crate are likely to be Ubuntu users.)
