### ISSUE TITLE
Enable Rust 2018

### ISSUE THREAD

**Issue by bheisler** [bheisler/RustaCUDA#17]
Make sure that everything compiles in Rust 2018 mode, then convert the code and all examples/rustdoc comments/tests/etc. to that mode.

**Comment by rusch95** [comment]
Eyyy, currently throws 171 errors on Rust 2018 mode

**Comment by rusch95** [comment]
Mainly resulting from ::path needing to be crate::path now

**Comment by bheisler** [comment]
Does rustfix help it at all? If it's difficult, it's fine to just leave it on 2015 until I get around to it later.

**Comment by rusch95** [comment]
Yeah, rust fix works beautifully. I just forgot to pass it the --edition flag first time around.

**Comment by rusch95** [comment]
There's just a few linter warnings to clean up. Do you want the bump on the derive and core crates as well.

**Comment by bheisler** [comment]
Enable the new edition for the subcrates, but don't change the crate version numbers. I'll do that when it's time to release a new version.

**Comment by bheisler** [comment]
This was partially implemented by #18 but the examples in the rustdoc and README still need to be updated.

**Comment by alphastrata** [comment]
Is there any further work required on this one?

**Comment by bheisler** [comment]
I'm not sure. The examples listed in the rustdoc and the README file still haven't been updated, but just off-hand I don't know what exactly would need to be changed (if anything).
