### ISSUE TITLE
How to do device-to-device memory allocations?

### ISSUE THREAD

**Issue by rasa200** [bheisler/RustaCUDA#36]
I am sorry if it is in the documentation, I can't find it in the DeviceBuffer section.

I would like to do something similar to the following instruction in CUDA:

cudaMemcpy(d_vec2, d_vec1, sizeof(d_vec1), cudaMemcpyDeviceToDevice);

which copies d_vec1 (on device) to d_vec2 (on device too).

**Comment by rusch95** [comment]
I think there should be some DeviceBuffer unit tests that do the thing
you're looking for.

**Comment by rusch95** [comment]
I can give you a specific code snippet later today.

**Comment by rasa200** [comment]
Hey!! The answer is pretty straight forward: just use copy_to(), so

cudaMemcpy(d_vec2, d_vec1, sizeof(d_vec1), cudaMemcpyDeviceToDevice);

... is "equivalent" to ...

d_vec1.copy_to(&mut d_vec2);
or
d_vec2.copy_from(&mut d_vec1);

when d_vec1 and d_vec2 are DeviceBuffers of the same size
