### ISSUE TITLE
DeviceBox for Vectors of data

### ISSUE THREAD

**Issue by ChipsSpectre** [bheisler/RustaCUDA#42]
Hey,

I just discovered this project and it looks really interesting!

The way how data is allocated on the GPU device looks like this for a scalar value.

`let mut factor1 = DeviceBox::new(&6.0f32)?;`

How can we allocate a vector of values on the device?
For example: If we want to increment all values in a vector `[1,2,3]`,
how can this vector be transferred to the device?

It would be great for me to to add this information to the API documentation
in order to help future users.

Best regards
Chips

**Comment by LutzCle** [comment]
Hi,

What you're looking for is [`DeviceBuffer`](https://bheisler.github.io/RustaCUDA/rustacuda/memory/struct.DeviceBuffer.html). The examples in the documentation show how you can transfer data to and from the device with `copy_to` and `copy_from`. You can also perform the copies asynchronously with `async_copy_to` and `async_copy_from`, see the documentation for [`AsyncCopyDestination`](https://bheisler.github.io/RustaCUDA/rustacuda/memory/trait.AsyncCopyDestination.html).

Hope that helps!

**Comment by ChipsSpectre** [comment]
Thank you really much, this helped a lot!
![grafik](https://user-images.githubusercontent.com/11499442/67493603-5c815900-f678-11e9-8788-0d5b0df73af8.png)
The device buffer is now used in a minimal version. Is it possible to add it to the examples section?

**Comment by LutzCle** [comment]
Looks almost exactly like the [existing launch example](https://github.com/bheisler/RustaCUDA/blob/master/examples/launch.rs) to me.

**Comment by ChipsSpectre** [comment]
I am sorry, I did not look into the _examples_ folder. Sometimes the solution is closer than one might think...

But nonetheless, thank you really much for mentioning the _DeviceBuffer_, I started to implement some kernels and **RustaCUDA** works great.  :+1:

**Comment by LutzCle** [comment]
Great that it's working for you now! I guess the README could link to the _examples_ folder to make the examples easier to find. Perhaps @bheisler would accept a pull request from you?

**Comment by ChipsSpectre** [comment]
:+1: 
Pull request created.

**Comment by bheisler** [comment]
Pull request has been merged.
