### ISSUE TITLE
Adding support for getting the UUID

### ISSUE THREAD

**Issue by vmx** [bheisler/RustaCUDA#55]
Currently there is no way to get the UUID of a device. I'd like to add this feature.

It's a matter of calling [`cuDeviceGetUuid()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1g987b46b884c101ed5be414ab4d9e60e4), which is already part of cuda-sys. There is also a [`cuDeviceGetUuid_v2()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1gdf3394a41af9cdb9f653386ed4991a1f), but that's a very recent addition (CUDA 11.4), so I would ignore it for now as `cuda-sys` is on CUDA 10.2 anyway.

I would implement `Device::uuid()`, similarly to the existing [`Device::name()`](https://bheisler.github.io/RustaCUDA/rustacuda/device/struct.Device.html#method.name).

Though `cuDeviceGetUuid()` is only available on `cuda-driver-sys` 0.3, which seems to be the successor of `cuda-sys` 0.2. Upgrading to it seems to work with minimal changes, I can also provide a PR for that (my current version of those changes is at https://github.com/vmx/RustaCUDA/tree/uuid).

**Comment by bheisler** [comment]
Hello! Thanks for the suggestion. Yes, a pull request would be welcome.
