### ISSUE TITLE
Add support for Events

### ISSUE THREAD

**Issue by bheisler** [bheisler/RustaCUDA#6]
Build a safe, rusty wrapper for the [Events](https://docs.nvidia.com/cuda/archive/8.0/cuda-driver-api/group__CUDA__EVENT.html#group__CUDA__EVENT) module.

Don't expose the `cuStreamBatchMemOp`, `cuStreamWaitValue32` or `cuStreamWriteValue32` functions, as they're deprecated in version 10 anyway.

**Comment by LutzCle** [comment]
Hi,

I've created an initial Event type for RustaCUDA [here](https://github.com/LutzCle/RustaCUDA/tree/cuda-event). So far it's just some code without documentation or tests. But perhaps you could take a look and comment if this is going in the right direction?

Cheers

**Comment by bheisler** [comment]
This looks pretty good so far. A few comments:

I did notice that many of the functions return `CudaResult<&Self>` - most of these have no real return value, so I'd prefer to return `CudaResult<()>`.

`query` should return a new enum - the underlying API uses the `CUresult` return value to indicate whether the event has been processed or not, but we should separate error-handling from the valid return values.

It might be better for `elapsed_time` to return a `std::time::Duration` but there isn't an easy way to construct one from floating-point milliseconds. I'm not sure about this; could go either way.

Naturally, tests, documentation and documentation-tests will be needed.

**Comment by LutzCle** [comment]
Thank you for your feedback, I appreciate it! I'll push an update in the next days.

**Comment by LutzCle** [comment]
See [this new commit](https://github.com/LutzCle/RustaCUDA/blob/cuda-event/src/event.rs) - I believe I've addressed your comments.

Concerning `elapsed_time` returing `std::time::Duration`, there [exists a tracking issue for duration_float](https://github.com/rust-lang/rust/issues/54361) on the Rust issue tracker. This would be perfect for implementing `elapsed_time`. However, it's still unstable as of now. Thus, I propose we rename `elapsed_time` to `elapsed_time_f32` (as per my commit above) and add a new function returning a `Duration` when the issue becomes stable.

The general idea would be to convert the `f32` value using `Duration::as_secs_f32`, and then rescale to milliseconds using `Duration.mul_f32`.

One more idea would be to use session types to ensure that `record` has been called on the events before calling `elapsed_time` (i.e., `fn record(e: Event) -> RecordedEvent`). An open question for me is what other functions besides `elapsed_time` require `record` to be called? `query` and `synchronize` would be the obvious candidates, but [the documentation](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__EVENT.html#group__CUDA__EVENT) isn't very specific about those.

However, care would have to be taken to ensure that `record` (and other function) can still be called multiple times on the same event. A possible solution would be to make `Event` a trait. Then again, this clearly adds complexity to the design.

What do you think?

**Comment by bheisler** [comment]
Yikes, thanks for your patience on this.

I'd say this is good enough to be merged. Would you mind submitting a pull request so I can merge it in?

**Comment by LutzCle** [comment]
Sorry that it took so long. I meant to add `Stream::wait_event` as well. The PR is ready now.
